name: Check PR Title

description: PR 생성 시 PR 제목이 Conventional Commit에 맞는 지 확인한다.

inputs:
  pullRequest:
    description: >
      생성된 PR 정보를 가져오기 위한 context 입니다.
      e.g.
      format(
        '{{ "title": {0} }}',
        toJSON(github.event.pull_request.title)
      )

runs:
  using: "node20"
  main: "dist/index.js"
