name: Check PR Lint
description: PR 생성 시, 변경된 파일들이 ESLint 규칙에 맞는지 확인합니다.
inputs:
  githubToken:
    description: >
      Github authentication에 필요한 App의 PAT입니다.
      e.g. secrets.GITHUB_TOKEN
  filePattern:
    description: >
      린트 검사할 파일의 패턴
      e.g. '^src/.*\.(js|ts|vue)$'
  baseName: 
    description: >
      타겟 브랜치의 베이스 브랜치
      e.g. github.base_ref
  pullRequest:
    description: >
      생성된 PR의 정보를 가져오기 위한 context 입니다.
      e.g.
      format(
        '{{ "baseName": {0}, "title": {1}, "url": {2} }}',
        toJSON(github.base_ref),
        toJSON(github.event.pull_request.title),
        toJSON(github.event.pull_request.html_url)
      )

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.2

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Fetch Base Branch
      shell: bash
      run: |
        git fetch origin ${{ inputs.baseName }}:refs/remotes/origin/${{ inputs.baseName }}
        echo "Base branch is ${{ inputs.baseName }}"

    - name: Get Changed Files
      id: changed-files
      shell: bash
      run: |
        CHANGED_FILES=$(git diff --name-only --diff-filter=ACMR origin/${{ inputs.baseName }} | grep -E "${{ inputs.filePattern }}" || echo "")
        echo "Changed files are: $CHANGED_FILES"
        echo "::set-output name=changedFiles::$CHANGED_FILES"

    - name: Run ESLint
      id: lint
      if: steps.changed-files.outputs.changedFiles != ''
      shell: bash
      run: |
        npx eslint ${{ steps.changed-files.outputs.changedFiles }}
      continue-on-error: true

    - name: Save ESLint Results
      if: steps.lint.outcome == 'failure' && steps.changed-files.outputs.changedFiles != ''
      shell: bash
      run: |
        npx eslint --output-file lint_report.json --format json ${{ steps.changed-files.outputs.changedFiles }}
      continue-on-error: true

    - name: Annotate ESLint Results
      if: steps.lint.outcome == 'failure' && steps.changed-files.outputs.changedFiles != ''
      uses: ataylorme/eslint-annotate-action@v3
      with:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
        report-json: lint_report.json
      continue-on-error: true

    - name: On Failed
      if: steps.lint.outcome == 'failure' && steps.changed-files.outputs.changedFiles != ''
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.githubToken }}
        script: |
          github.rest.issues.createComment({
            repo: context.repo.repo,
            owner: context.repo.owner,
            issue_number: context.issue.number,
            body: ':warning: ESLint 오류가 발생했습니다.',
          })
